# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='controlmsg.proto',
  package='',
  serialized_pb='\n\x10\x63ontrolmsg.proto\"B\n\x0e\x43ontrolMessage\x12\x13\n\x04type\x18\x01 \x02(\x0e\x32\x05.Type\x12\x0c\n\x04left\x18\x02 \x02(\x05\x12\r\n\x05right\x18\x03 \x02(\x05*\x1b\n\x04Type\x12\x07\n\x03SET\x10\x01\x12\n\n\x06\x43HANGE\x10\x02')

_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SET', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CHANGE', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=88,
  serialized_end=115,
)


SET = 1
CHANGE = 2



_CONTROLMESSAGE = descriptor.Descriptor(
  name='ControlMessage',
  full_name='ControlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='ControlMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left', full_name='ControlMessage.left', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right', full_name='ControlMessage.right', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=86,
)

_CONTROLMESSAGE.fields_by_name['type'].enum_type = _TYPE
DESCRIPTOR.message_types_by_name['ControlMessage'] = _CONTROLMESSAGE

class ControlMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLMESSAGE
  
  # @@protoc_insertion_point(class_scope:ControlMessage)

# @@protoc_insertion_point(module_scope)
